# Generated by Django 3.0.3 on 2020-02-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skl', models.CharField(max_length=30)),
                ('reg', models.IntegerField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vac', models.CharField(max_length=30)),
                ('reg', models.CharField(max_length=30)),
                ('num', models.IntegerField(max_length=8)),
            ],
        ),
    ]
