# Generated by Django 3.0.3 on 2020-02-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skl',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='num',
            field=models.IntegerField(blank=True, max_length=8),
        ),
    ]
