# Generated by Django 3.0.3 on 2020-02-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxapp', '0002_auto_20200216_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='reg',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skl',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
