# Generated by Django 3.0.3 on 2020-02-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxapp', '0003_auto_20200216_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='num',
            field=models.IntegerField(blank=True),
        ),
    ]
