# Generated by Django 3.0.3 on 2020-02-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxapp', '0004_auto_20200216_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.TextField(blank=True)),
                ('ul', models.URLField(max_length=256)),
            ],
        ),
    ]
