# Generated by Django 3.0.3 on 2020-05-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xxapp', '0003_article_is_active'),
        ('xxapp', '0005_article'),
    ]

    operations = [
    ]
